### ISSUE TITLE
Tablas de verdad

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-2363#1]
[Tablas de verdad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-2363/files/13222768/Tablas.de.verdad.pdf)

**Comment by JoseRodriguez-23620213** [comment]
Portada: 25
Procedimiento : 22
Figuras: 25
Resultados: 25
Total: 97 Cal.Final: 19.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
